module.exports = {
  apps: [
    {
      name: 'madebuy-admin-dev',
      cwd: './apps/admin',
      script: 'node_modules/next/dist/bin/next',
      args: 'dev -p 3300',
      env: {
        NODE_ENV: 'development',
        PORT: 3300,
      },
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
      error_file: './logs/admin-dev-error.log',
      out_file: './logs/admin-dev-out.log',
      time: true,
    },
    {
      name: 'madebuy-web-dev',
      cwd: './apps/web',
      script: 'node_modules/next/dist/bin/next',
      args: 'dev -p 3301',
      env: {
        NODE_ENV: 'development',
        PORT: 3301,
      },
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
      error_file: './logs/web-dev-error.log',
      out_file: './logs/web-dev-out.log',
      time: true,
    },
    {
      name: 'madebuy-manager-dev',
      cwd: './apps/manager',
      script: 'node_modules/next/dist/bin/next',
      args: 'dev -p 3399',
      env: {
        NODE_ENV: 'development',
        PORT: 3399,
      },
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
      error_file: './logs/manager-dev-error.log',
      out_file: './logs/manager-dev-out.log',
      time: true,
    },
  ],
}
