module.exports = {
  apps: [
    {
      name: 'madebuy-admin',
      cwd: '/app/apps/admin',
      script: './node_modules/next/dist/bin/next',
      args: 'start -p 3300',
      interpreter: 'node',
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'production',
        PORT: 3300,
      },
      autorestart: true,
      watch: false,
      max_memory_restart: '768M',
      error_file: '/app/logs/admin-error.log',
      out_file: '/app/logs/admin-out.log',
      time: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
    },
    {
      name: 'madebuy-web',
      cwd: '/app/apps/web',
      script: './node_modules/next/dist/bin/next',
      args: 'start -p 3301',
      interpreter: 'node',
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'production',
        PORT: 3301,
      },
      autorestart: true,
      watch: false,
      max_memory_restart: '768M',
      error_file: '/app/logs/web-error.log',
      out_file: '/app/logs/web-out.log',
      time: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
    },
    {
      name: 'madebuy-manager',
      cwd: '/app/apps/manager',
      script: './node_modules/next/dist/bin/next',
      args: 'start -p 3399',
      interpreter: 'node',
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'production',
        PORT: 3399,
      },
      autorestart: true,
      watch: false,
      max_memory_restart: '512M',
      error_file: '/app/logs/manager-error.log',
      out_file: '/app/logs/manager-out.log',
      time: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
    },
  ],
}
